### ISSUE TITLE
installing redux-injectors without --force or --legacy-peer-deps

### ISSUE THREAD

**Issue by avx99** [react-boilerplate/redux-injectors#41] opened 2022-09-25 09:47 UTC
I am trying to work with redux saga (React 18.2.0), I configured the store, the reducer and the request, so to do the API call I decided to inject the reducer and saga using ```useInjectReducer``` and ```useInjectSaga``` from ```redux-injectors``` :
```
import { useInjectReducer, useInjectSaga } from 'redux-injectors';
```
the problem is that when I try to install ```redux-injectors``` I got this error: 
```
npm install redux-injectors
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: test-socle@0.1.0
npm ERR! Found: react@18.2.0
npm ERR! node_modules/react
npm ERR!   react@"^18.2.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.6.0 || ^17.0.0" from redux-injectors@2.0.0
npm ERR! node_modules/redux-injectors
npm ERR!   redux-injectors@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\Admin\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Admin\AppData\Local\npm-cache\_logs\2022-09-25T09_19_46_303Z-debug-0.log
```

I locked up for the solution, and I found that I need to add ```--legacy-peer-deps``` or ```--force``` while installing, this solution works fine in my local machine, but it will not work at the dev environment because at this environment we install dependencies only using ```npm install```

**Comment by KonradLinkowski** [comment] 2022-09-25 10:11
Probably duplicate of #34

**Comment by BenLorantfy** [comment] 2022-09-29 23:46
Closing as duplicate of #34

**Closed by BenLorantfy** 2022-09-29 23:46 UTC
